export const theme = {
  colors: {
    body: '#e7ecf2',
    black: '#000',
    white: '#fff',
    grey: '#f3f6f9',
    textGrey: '#8e9ca8',
    text: '#2a2a2a',
    background: '#fff',
    primary: '#07c',
    secondary: '#e7ecf2',
    accent: '#609',
    muted: '#f6f6f6',
    darkGrey: '#c7c7c7',
    statsColor: '#fff',
  },
  space: [0, 2, 4, 8, 16, 32, 64, 128, 256],
  fonts: {
    body: 'system-ui, sans-serif',
    heading: 'system-ui, sans-serif',
    monospace: 'Menlo, monospace',
  },
  fontSizes: {
    xs: '12px',
    s: '14px',
    ms: '16px',
    m: '20px',
    ml: '24px',
    l: '32px',
    xl: '64px',
  },
  fontWeights: {
    normal: 400,
    midle: 500,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  borders: {
    none: 'none',
    normal: '1px solid',
  },
  radii: {
    none: '0',
    normal: '4px',
    round: '50%',
  },
};
